[build]
  command = "npm run production"
  publish = "build_production"
  environment = { PHP_VERSION = "7.2" }
  functions = "./api"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Upgrade-Insecure-Requests = "1"
    Referrer-Policy = "no-referrer-when-downgrade"
    Feature-Policy = "geolocation 'none'; midi 'none'; notifications 'self'; push 'self'; sync-xhr 'self'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'self'; vibrate 'self'; fullscreen 'self'; payment 'self'"
