backend:
  name: rpg-do-mestre-git-gateway
display_url: https://www.rpgdomestre.com

publish_mode: editorial_workflow
media_folder: "source/assets/images/uploads"
public_folder: "assets/images/uploads"

collections:
  - name: 'weekly'
    label: 'Weekly'
    label_singular: 'Weekly'
    description: >
      Our Weekly section that will be generated
    folder: '_weekly'
    slug: '{{slug}}'
    extension: 'blade.md'
    format: 'yaml-frontmatter'
    create: true
    fields:
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
    meta:
      - { label: 'Weekly Edition Title', name: 'mSubtitle', widget: 'text', required: true, default: 'Edição' }
      - { label: 'Published Date', name: 'date', widget: 'text', format: 'YYYY-MM-DD' required: true, default: '' }
      - { label: 'Extends Layout', name: 'extends', widget: 'text', required: true, default: '_layouts.markdown' }
      - { label: 'Layout Section to Update', name: 'section', widget: 'text', required: true, default: 'mContent' }
      - { label: 'Collection Base Title', name: 'mTitle', widget: 'text', required: true, default: 'Weekly' }
      - { label: 'Is it Active?', name: 'mActive', widget: 'boolean', required: true, default: true }
      - { label: 'Is Subheader Shown?', name: 'mSubheader', widget: 'boolean', required: true, default: true }
      - { label: 'Is Navigation Shown?', name: 'mNavigation', widget: 'boolean', required: true, default: true }
      - { label: 'Is Layout Section Primary?', name: 'mSectionPrimary', widget: 'boolean', required: true, default: false }
      - { label: 'Does Use Collection Title for Page Title?', name: 'mUseMTitleForPageTitle', widget: 'boolean', required: true, default: true }
      - { label: 'DOM Class to apply', name: 'mContentClasses', widget: 'text', required: true, default: 'weekly' }