backend:
  name: git-gateway
display_url: https://www.rpgdomestre.com

publish_mode: editorial_workflow
media_folder: "source/assets/images/uploads"
public_folder: "assets/images/uploads"

collections:
  - name: "weekly"
    label: "Weekly"
    label_singular: "Weekly"
    description: >
      Our Weekly section that will be generated
    folder: "source/_weekly"
    slug: "{{slug}}"
    extension: "blade.md"
    format: "yaml-frontmatter"
    create: true
    identifier_field: "number"
    fields:
      - { label: "Weekly Edition Number", name: "number", widget: "string", required: true, default: "" }
      - { label: "Weekly Edition Title", name: "mSubtitle", widget: "string", required: true, default: "Edição " }
      - { label: "Published Date", name: "date", widget: "date", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", required: true, default: "" }
      - { label: "Body", name: "body", widget: "markdown", hint: "Main content goes here." }
      - { name: "extends", widget: "string", required: true, default: "_layouts.markdown" }
      - { name: "section", widget: "string", required: true, default: "mContent" }
      - { name: "mTitle", widget: "string", required: true, default: "Weekly" }
      - { name: "mActive", widget: "boolean", required: true, default: true }
      - { name: "mSubheader", widget: "boolean", required: true, default: true }
      - { name: "mNavigation", widget: "boolean", required: true, default: true }
      - { name: "mSectionPrimary", widget: "boolean", required: true, default: false }
      - { name: "mUseMTitleForPageTitle", widget: "boolean", required: true, default: true }
      - { name: "mContentClasses", widget: "string", required: true, default: "weekly" }